### ISSUE TITLE
react-native link failed

### ISSUE THREAD

**Issue by vhontar** [jacklam718/react-native-button-component#22]
Hi) I want to thank you for your awesome component, but i have error when i tried to link:

Scanning 759 folders for symlinks in .../node_modules (8ms)
[react-native-button-component] - linking native dependencies
.../node_modules/react-native-spinkit/scripts/rnpm-prelink.js:21
var str = depStr[0];
                ^

TypeError: Cannot read property '0' of null
    at Object.<anonymous> (.../node_modules/react-native-spinkit/scripts/rnpm-prelink.js:21:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
.../node_modules/react-native/local-cli/core/makeCommand.js:29
        throw new Error(`Error occured during executing "${command}" command`);

it's like react-native-spinkit/scripts/rnpm-prelink.js:21 -> depStr doesn't have elements inside and it caused errors, that's why i don't see button.
Could you resolve this bug or tell me what to do?
OS: Ubuntu 17.04
RN: 0.46
react-native-button-component: 0.1.18 (latest)

**Comment by vhontar** [comment]
My fault, i didn't detach the project, exp detatch
